### ISSUE TITLE
Aslo support whole directories upload

### ISSUE THREAD

**Issue by pombredanne** [google/github-release-retry#3]
It would useful to be able to point to a directory (as opposed to one or more files) to upload its content recursively.
And thanks ++ for this tool!
We are using github-release-retry in scancode release handling to maintain a our own "PyPI" like repo of pre-built wheels at https://github.com/nexB/thirdparty-packages/releases/tag/pypi
@Abhishek-Dev09 worked out a simple wrapper to walk a directory at  https://github.com/nexB/scancode-toolkit/blob/develop/etc/scripts/github_release.py#L72 but it would much simpler to have this baked in upstream here.
Do you want a PR?

**Comment by paulthomson** [comment]
Sounds good! Thanks for using it!

If you want to improve the `github-release-retry` command line tool so that it can optionally take directories (perhaps with a `-r, --recursive` flag), then I am happy to receive a PR, or I can add that myself. However, I would also ask: why not just do something like this from your shell:

`github-release-retry --user paul [...other args...] files_to_upload/*`

Would this work for your use case?

If you want to change the `make_release` function in the `github-release-retry` library, then I would say that your current approach is the right approach; I prefer to have `make_release` take a list of files, with no directories.

**Comment by pombredanne** [comment]
>  However, I would also ask: why not just do something like this from your shell:
> `github-release-retry --user paul [...other args...] files_to_upload/*`
> Would this work for your use case?

Of course! that's much cleaner. I cannot think of a use case where this would not work.
